language: d
d:
  - dmd
  - ldc
sudo: false
matrix:
  include:
    - d: 'dmd'
      env: CONFIG=default
    - d: 'ldc'
      env: CONFIG=default
  allow_failures:
    - d: 'dmd'
      env: CONFIG=ssl
script: dub test -c $CONFIG
