#!/bin/bash

UI1="$(echo $1 | tr  '[:upper:]' '[:lower:]')"
CFLAGS=""

if [ "$UI1" == "ssl" ]; then
    echo "Compiling: DaNode openSSL version"
    CFLAGS="-version=SSL -I../openssl -L-lssl -L-lcrypto"
fi

rdmd --force --build-only -O -gc -release $CFLAGS -w danode/server.d

