#!/bin/bash

UI1="$(echo $1 | tr  '[:upper:]' '[:lower:]')"
CFLAGS=""

if [ "$UI1" == "ssl" ]; then
    echo "Compiling: DaNode openSSL version"
    CFLAGS="--config=ssl"
fi

dub build --force --build=release $CFLAGS

