#!/usr/bin/env bash

if pgrep -f 'bin/server' >/dev/null 2>&1
  then
     echo "Running"
  else
     echo "Down, restarting"
     cd /home/danny/Github/DaNode/
     nohup authbind bin/server -k -b 100 -v 0 > /dev/null 2>&1 &
     date >> /home/danny/restarts.txt
fi

