module danode.cgi;

import danode.imports;
import danode.functions : Msecs, bodystart, endofheader, fullheader;
import danode.log : log, tag, error, Level;
import danode.router : Router, runRequest;
import danode.interfaces : StringDriver;
import danode.process : Process;
import danode.statuscode : StatusCode;
import danode.payload : HeaderType, Payload, PayloadType;

// Class structure for common gateway interface (CGI) scripts
class CGI : Payload {
  private:
    Process external;

  public:
    string command;

    this(string[] command, string path, string[string] environ, bool removeInput = true, long maxtime = 4500){
      this.command = command.join(" ");
      external = new Process(command, path, environ, removeInput, maxtime); 
      external.start();
    }

    // The sort of payload carried (PayLoadType.Script)
    final @property PayloadType type() const { return(PayloadType.Script); }

    // Ready to start sending ?
    final @property long ready() { 
        if (external.finished) return(true);
        return(endOfHeader > 0);
    }

    // length of the message portion of the output (generated HTTP headers are detected and substracted)
    final @property ptrdiff_t length() const {
      if (!external.running) {
        ptrdiff_t msglength = to!ptrdiff_t(external.length);
        if(endOfHeader > 0) msglength = msglength - bodyStart;
        return(getHeader!ptrdiff_t("Content-Length", msglength));
      }
      return -1; 
    }

    @property void notifyovertime() { external.notifyovertime(); }

    // Last modified time (not interesting for scripts)
    final @property SysTime mtime() { return Clock.currTime(); }

    // MIME type of the content: "Content-Type: text/html; charset=utf-8"
    // split by ; since the Content-Type might be combined with a charset
    final @property string mimetype() const { 
      auto type = getHeader("Content-Type", "text/html");
      return(type.split(";")[0]);
    }

    // Get a header value from the header generated by the script
    final T getHeader(T)(string key, T def = T.init) const {
      if (endOfHeader > 0) {
        foreach (line; fullHeader().split("\n")) {
          string[] elems = line.split(": ");
          if (elems.length == 2) { if (icmp(elems[0], key) == 0) return(to!T(strip(elems[1]))); }
        }
      }
      return(def);
    }

    private const(char)[] rawOutput() const {
      return cast(const(char)[]) external.output(0);
    }

    // Type of header returned by the script: FastCGI, HTTP10, HTTP11
    @property final HeaderType headerType() const {
      if (endOfHeader <= 0) return HeaderType.None;
      string[] values = firstHeaderLine().split(" ");
      if (values.length >= 3 && values[0] == "HTTP/1.0") return HeaderType.HTTP10;
      if (values.length >= 3 && values[0] == "HTTP/1.1") return HeaderType.HTTP11;
      if (getHeader("Status", "") != "") return HeaderType.FastCGI;
      //if (getHeader("Content-Type", "") != "") return HeaderType.FastCGI;
      return HeaderType.None;
    }

    // Get the full header generated by the script
    @property final string fullHeader() const { return(fullheader(rawOutput())); }

    // Get the first line of the header
    @property final string firstHeaderLine() const {
      auto o = rawOutput();
      ptrdiff_t i = o.indexOf('\n');
      return(to!string(i > 0 ? o[0 .. i] : o));
    }

    // Return the status code provided by the external script
    @property final StatusCode statuscode() const {
      string status = "";
      auto htype = headerType();
      if (htype == HeaderType.FastCGI) { status = getHeader!string("Status", "").split(" ")[0]; }
      if (htype == HeaderType.HTTP10 || htype == HeaderType.HTTP11) {
        string[] values = firstHeaderLine().split(" ");
        if(values.length >= 3) status = values[1];
      }
      if (status == "") {
        if (external.status == 0) return StatusCode.Ok;
        if (!external.running && external.timedOut()) return StatusCode.TimedOut;
        return StatusCode.ISE;
      }
      try {
        int code = to!int(status);
        foreach (immutable v; EnumMembers!StatusCode) { if (v.code == code) return v; }
      } catch (Exception e) { error("unable to get statuscode from script"); }
      return StatusCode.ISE;
    }

    @property bool contentLengthValid() const {
      if (endOfHeader < 0) return false;
      ptrdiff_t actual = to!ptrdiff_t(external.length) - bodyStart;
      ptrdiff_t claimed = getHeader!ptrdiff_t("Content-Length", -1);
      return claimed == actual;
    }

    // Stream of message bytes, skips the script generated header since the webserver 
    // parses the header and generates it's own
    final const(char)[] bytes(ptrdiff_t from, ptrdiff_t maxsize = 4096, bool isRange = false, long rangeStart = 0, long rangeEnd = -1) {
      auto o = rawOutput();
      ptrdiff_t start = endofheader(o) > 0 ? bodystart(o) : 0;
      from += start;
      return o[from .. to!ptrdiff_t(min(from+maxsize, $))];
    }

    // Position of the end of the header
    @property final ptrdiff_t endOfHeader() const { return(endofheader(rawOutput())); }
    // Position of the start of the body
    @property final ptrdiff_t bodyStart() const { return(bodystart(rawOutput())); }
}


unittest {
  tag(Level.Always, "FILE", "%s", __FILE__);

  auto router = new Router("./www/", Address.init);

  // Warmup - ensure rdmd cache is hot before timed tests
  tag(Level.Always, "WARMUP", "compiling CGI scripts...");
  router.runRequest("GET /dmd.d HTTP/1.1\nHost: localhost\n\n", 5000);
  router.runRequest("GET /keepalive.d HTTP/1.1\nHost: localhost\n\n", 5000);
  router.runRequest("GET /ISE1.d HTTP/1.1\nHost: localhost\n\n", 5000);
  router.runRequest("GET /ISE2.d HTTP/1.1\nHost: localhost\n\n", 5000);
  router.runRequest("GET /ISE3.d HTTP/1.1\nHost: localhost\n\n", 5000);
  tag(Level.Always, "WARMUP", "done");

  StringDriver res;
  // dmd.d has wrong Content-Length - must force Close
  res = router.runRequest("GET /dmd.d HTTP/1.1\nHost: localhost\nConnection: keep-alive\n\n");
  assert(res.lastStatus == StatusCode.Ok, format("dmd.d expected 200, got %d", res.lastStatus.code));
  assert(icmp(res.lastConnection, "close") == 0, format("dmd.d must force Close, got %s", res.lastConnection));

  // keepalive.d has correct Content-Length - must honour keep-alive
  res = router.runRequest("GET /keepalive.d HTTP/1.1\nHost: localhost\nConnection: keep-alive\n\n");
  assert(res.lastStatus == StatusCode.Ok, format("keepalive.d expected 200, got %d", res.lastStatus.code));
  assert(icmp(res.lastConnection, "keep-alive") == 0, format("keepalive.d must keep-alive, got %s", res.lastConnection));
}
